
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mjed
 */
public class Add_dependant extends javax.swing.JFrame {

    /**
     * Creates new form Add_dependant
     */
    public Add_dependant() {
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dep_mname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dep_lname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dep_phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dep_fname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emp_ID = new javax.swing.JTextField();
        dep_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dep_mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dep_mnameActionPerformed(evt);
            }
        });

        jLabel6.setText("Last Name");

        dep_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dep_lnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Adding Dependent");

        jLabel3.setText("Phone");

        dep_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dep_phoneActionPerformed(evt);
            }
        });

        jLabel4.setText("First Name");

        dep_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dep_fnameActionPerformed(evt);
            }
        });

        jLabel5.setText("Middle Name");

        jLabel8.setText("Employee ID");

        emp_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_IDActionPerformed(evt);
            }
        });

        dep_add.setText("Add");
        dep_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dep_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(dep_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dep_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(21, 21, 21)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dep_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dep_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(emp_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel2)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dep_add)
                .addGap(221, 221, 221))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dep_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dep_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dep_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dep_mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emp_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(dep_add)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dep_mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dep_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dep_mnameActionPerformed

    private void dep_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dep_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dep_lnameActionPerformed

    private void dep_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dep_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dep_phoneActionPerformed

    private void dep_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dep_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dep_fnameActionPerformed

    private void emp_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_IDActionPerformed

    private void dep_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dep_addActionPerformed
        // TODO add your handling code here:
        try {
            if (dep_phone.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Phone is empty.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (dep_fname.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "First name is empty", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (dep_mname.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Middle  name is empty", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (dep_lname.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Last name is empty.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (emp_ID.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Employee ID is empty.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
//insert into Dependent values(0532512490,'Saeed', 'Mastour', 'AlHarbi', 7);
                String querue = "insert into Dependent values(" + dep_phone.getText() + ",'" + dep_fname.getText() + "','" + dep_mname.getText() + "','" + dep_lname.getText() + "'," + emp_ID.getText() +")";
                Statement st = con.prepareStatement(querue);
                ResultSet rs = st.executeQuery(querue);

                querue = "commit";
                st = con.prepareStatement(querue);
                rs = st.executeQuery(querue);

                JOptionPane.showMessageDialog(this, "Dependant Added");
                this.setVisible(false);
                this.dispose();

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());

        }

    }//GEN-LAST:event_dep_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_dependant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_dependant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_dependant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_dependant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_dependant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dep_add;
    private javax.swing.JTextField dep_fname;
    private javax.swing.JTextField dep_lname;
    private javax.swing.JTextField dep_mname;
    private javax.swing.JTextField dep_phone;
    private javax.swing.JTextField emp_ID;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    Connection con;

    public void setConnection(Connection con) {
        this.con = con;
    }
}
