
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mjed
 */
public class Add_emp extends javax.swing.JFrame {

    /**
     * Creates new form Add_emp
     */
    public Add_emp() {
        initComponents();
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emp_ssn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emp_fname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emp_mname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emp_lname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emp_gender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emp_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emp_address = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        emp_email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emp_supID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emp_wh_id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emp_fd_id = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        emp_salary = new javax.swing.JTextField();
        add_emp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        emp_ph1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        emp_ph2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        emp_ph3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Adding Employee");

        jLabel3.setText("SSN");

        emp_ssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_ssnActionPerformed(evt);
            }
        });

        jLabel4.setText("First Name");

        emp_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_fnameActionPerformed(evt);
            }
        });

        jLabel5.setText("Middle Name");

        emp_mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_mnameActionPerformed(evt);
            }
        });

        jLabel6.setText("Last Name");

        emp_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_lnameActionPerformed(evt);
            }
        });

        jLabel7.setText("Gender");

        emp_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_genderActionPerformed(evt);
            }
        });

        jLabel8.setText("Employee ID");

        emp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_idActionPerformed(evt);
            }
        });

        jLabel9.setText("Address");

        emp_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_addressActionPerformed(evt);
            }
        });

        jLabel11.setText("Email");

        emp_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_emailActionPerformed(evt);
            }
        });

        jLabel10.setText("Supervisor ID");

        emp_supID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_supIDActionPerformed(evt);
            }
        });

        jLabel12.setText("Warehouse ID");

        emp_wh_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_wh_idActionPerformed(evt);
            }
        });

        jLabel13.setText("Finance Dept ID");

        emp_fd_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_fd_idActionPerformed(evt);
            }
        });

        jLabel14.setText("Salary");

        emp_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_salaryActionPerformed(evt);
            }
        });

        add_emp.setText("Add");
        add_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_empActionPerformed(evt);
            }
        });

        jLabel15.setText("Phone 1");

        emp_ph1.setToolTipText("Optional");
        emp_ph1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_ph1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Phone 2");

        emp_ph2.setToolTipText("Optional");
        emp_ph2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_ph2ActionPerformed(evt);
            }
        });

        jLabel17.setText("Phone 3");

        emp_ph3.setToolTipText("Optional");
        emp_ph3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_ph3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_emp)
                .addGap(280, 280, 280))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(emp_ph1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(emp_ph2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(emp_ph3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(emp_address, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(emp_email)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(emp_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(emp_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(emp_mname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(17, 17, 17)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(emp_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(emp_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(emp_supID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(emp_wh_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(emp_fd_id, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(emp_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_mname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_supID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_wh_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_fd_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_ph1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_ph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emp_ph3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(add_emp)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emp_ssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_ssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_ssnActionPerformed

    private void emp_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_fnameActionPerformed

    private void emp_mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_mnameActionPerformed

    private void emp_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_lnameActionPerformed

    private void emp_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_genderActionPerformed

    private void emp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_idActionPerformed

    private void emp_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_addressActionPerformed

    private void emp_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_emailActionPerformed

    private void emp_supIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_supIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_supIDActionPerformed

    private void emp_wh_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_wh_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_wh_idActionPerformed

    private void emp_fd_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_fd_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_fd_idActionPerformed

    private void emp_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_salaryActionPerformed

    private void emp_ph1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_ph1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_ph1ActionPerformed

    private void emp_ph2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_ph2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_ph2ActionPerformed

    private void emp_ph3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_ph3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_ph3ActionPerformed

    private void add_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_empActionPerformed
        // TODO add your handling code here:

        try {
            if (emp_ssn.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "SSN is empty.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (emp_fname.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "First name is empty", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (emp_mname.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Middle  name is empty", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (emp_lname.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Last name is empty.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ((!emp_gender.getText().equalsIgnoreCase("M")) && (!emp_gender.getText().equalsIgnoreCase("F"))) {
                JOptionPane.showMessageDialog(this, "Please enter M or F in gender.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (emp_id.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Employee id is empty.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (emp_address.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "address is empty.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (emp_email.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Email is empty.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (emp_supID.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Supervisour ID is empty.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (emp_wh_id.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Warehouse ID is empty.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (emp_fd_id.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "FinanceDept ID is empty.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (emp_salary.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Salary is empty.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String querue = "insert into Employee values(" + emp_ssn.getText() + ",'" + emp_fname.getText() + "','" + emp_mname.getText() + "','" + emp_lname.getText() + "'," + emp_id.getText() + ",'" + emp_address.getText() + "','" + emp_email.getText() + "','" + emp_gender.getText() + "'," + emp_salary.getText() + "," + emp_supID.getText() + "," + emp_wh_id.getText() + "," + emp_fd_id.getText() + ")";
                Statement st = con.prepareStatement(querue);
                ResultSet rs = st.executeQuery(querue);

                querue = "commit";
                st = con.prepareStatement(querue);
                rs = st.executeQuery(querue);

                JOptionPane.showMessageDialog(this, "Employee Added");
                this.setVisible(false);
                this.dispose();

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());

        }


    }//GEN-LAST:event_add_empActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_emp().setVisible(true);
            }
        });
    }
    Connection con;

    public void setConnection(Connection con) {
        this.con = con;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_emp;
    private javax.swing.JTextField emp_address;
    private javax.swing.JTextField emp_email;
    private javax.swing.JTextField emp_fd_id;
    private javax.swing.JTextField emp_fname;
    private javax.swing.JTextField emp_gender;
    private javax.swing.JTextField emp_id;
    private javax.swing.JTextField emp_lname;
    private javax.swing.JTextField emp_mname;
    private javax.swing.JTextField emp_ph1;
    private javax.swing.JTextField emp_ph2;
    private javax.swing.JTextField emp_ph3;
    private javax.swing.JTextField emp_salary;
    private javax.swing.JTextField emp_ssn;
    private javax.swing.JTextField emp_supID;
    private javax.swing.JTextField emp_wh_id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
